/**
 * v2 round-trip stability test.
 *
 * Principle 3 (design lock): serialize(parse(source)) must be byte-for-byte
 * identical to serialize(parse(serialize(parse(source)))).
 */
import { describe, it, expect } from 'vitest';
import { parseTable }     from '../src/parser';
import { serializeTable } from '../src/serializer';

// ── Test fixtures ─────────────────────────────────────────────────────────────

const FIXTURES = [
	{
		name: 'minimal table',
		source: `---
version: 2
columns:
  - id: c_000000
    name: A
rows:
  - id: r_000000
    cells:
      c_000000: hello
---
<!-- Generated by Rich Table. Do not edit below — data source is the YAML front-matter above. -->
| A     |
| ----- |
| hello |`,
	},
	{
		name: 'table with styles, merges, filter, sort, aggregate, footer',
		source: `---
version: 2
columns:
  - id: c_000000
    name: 功能
    width: 101
  - id: c_000001
    name: 状态
    type: task-status
    width: 112
    filter:
      - done
rows:
  - id: r_000000
    cells:
      c_000000: 编辑单元格
      c_000001: done
  - id: r_000001
    height: 56
    cells:
      c_000000: 双链补全
      c_000001: done
merges:
  - anchor: r_000000.c_000001
    end: r_000001.c_000001
styles:
  - target: header
    bg: "#e8f0fe"
    bold: true
  - target: r_000000.c_000000
    bold: true
footer: 测试
sort:
  colId: c_000000
  dir: asc
aggregate:
  - count
---
<!-- Generated by Rich Table. Do not edit below — data source is the YAML front-matter above. -->
| 功能       | 状态 |
| ---------- | ---- |
| 编辑单元格 | done |
| 双链补全   |      |`,
	},
	{
		name: 'hidden row and column',
		source: `---
version: 2
columns:
  - id: c_000000
    name: A
  - id: c_000001
    name: B
    hidden: true
rows:
  - id: r_000000
    cells:
      c_000000: visible
  - id: r_000001
    hidden: true
    cells:
      c_000000: hidden
---
<!-- Generated by Rich Table. Do not edit below — data source is the YAML front-matter above. -->
| A       |
| ------- |
| visible |`,
	},
	{
		name: 'table with title and locked',
		source: `---
version: 2
title: My Table
columns:
  - id: c_000000
    name: Col
rows:
  - id: r_000000
    cells:
      c_000000: value
locked: true
---
<!-- Generated by Rich Table. Do not edit below — data source is the YAML front-matter above. -->
| Col   |
| ----- |
| value |`,
	},
];

// ── Round-trip assertions ─────────────────────────────────────────────────────

describe('v2 round-trip stability', () => {
	for (const { name, source } of FIXTURES) {
		it(name, () => {
			const model1      = parseTable(source);
			const serialized1 = serializeTable(model1);
			const model2      = parseTable(serialized1);
			const serialized2 = serializeTable(model2);

			expect(serialized1).toBe(serialized2);
		});
	}
});

import { convertTargetV1toV2 } from '../src/migrations/v1_to_v2';

describe('convertTargetV1toV2', () => {
	const colId = (ci: number) => `c_${String(ci).padStart(6, '0')}`;
	const rowId = (di: number) => `r_${String(di).padStart(6, '0')}`;
	const cols = 4;
	const conv = (t: string) => convertTargetV1toV2(t, colId, rowId, cols);

	it('1:1 → header', ()           => expect(conv('1:1')).toBe('header'));
	it('B* → whole col',  ()         => expect(conv('B*')).toBe('c_000001'));
	it('*3 → whole row',  ()         => expect(conv('*3')).toBe('r_000001'));  // row3 = di=1
	it('2:4 → row range', ()         => expect(conv('2:4')).toBe('r_000000:r_000002'));
	it('A:C → col range', ()         => expect(conv('A:C')).toBe('c_000000:c_000002'));
	it('B3 → single cell', ()        => expect(conv('B3')).toBe('r_000001.c_000001'));
	// Single-column multi-row ranges must produce rect, NOT row ranges
	it('D3:D4 → rect (not row range)', () =>
		expect(conv('D3:D4')).toBe('r_000001.c_000003:r_000002.c_000003'));
	it('A2:A7 → rect (not row range)', () =>
		expect(conv('A2:A7')).toBe('r_000000.c_000000:r_000005.c_000000'));
	// Multi-column rect
	it('A1:C3 → rect clamped to data rows', () =>
		expect(conv('A1:C3')).toBe('r_000000.c_000000:r_000001.c_000002'));
});

describe('v1→v2 merge migration', () => {
	it('a header-only merge (A1:B1) migrates to the header sentinel, not a garbage row id', async () => {
		const { migrateV1toV2 } = await import('../src/migrations/v1_to_v2');
		const v1Source = `---
columns:
  - { name: 任务 }
  - { name: 子任务 }
merges:
  - "A1:B1"
---
| 任务 | 子任务 |
| ---- | ------ |
| a    | b      |`;

		const v2Source = migrateV1toV2(v1Source);
		expect(v2Source).toContain('anchor: header.c_000000');
		expect(v2Source).toContain('end: header.c_000001');
		// The bug this guards against: rowIdByDataIdx(-1) used to fall through to
		// seqId('r', -1), which is literally the string "r_0000-1".
		expect(v2Source).not.toContain('r_0000-1');

		// The migrated merge must actually resolve — round-tripping it through
		// parse/serialize should keep it intact rather than silently dropping it.
		const model = parseTable(v2Source);
		expect(model.merges).toEqual([{ anchor: 'header.c_000000', end: 'header.c_000001' }]);
	});

	it('a merge entirely within data rows is unaffected', async () => {
		const { migrateV1toV2 } = await import('../src/migrations/v1_to_v2');
		const v1Source = `---
columns:
  - { name: 任务 }
merges:
  - "A2:A3"
---
| 任务 |
| ---- |
| a    |
| b    |`;

		const model = parseTable(migrateV1toV2(v1Source));
		expect(model.merges).toEqual([{ anchor: 'r_000000.c_000000', end: 'r_000001.c_000000' }]);
	});

	it('a merge spanning both the header row and data rows is dropped, not guessed at', async () => {
		const { migrateV1toV2 } = await import('../src/migrations/v1_to_v2');
		const v1Source = `---
columns:
  - { name: 任务 }
merges:
  - "A1:A2"
---
| 任务 |
| ---- |
| a    |`;

		const model = parseTable(migrateV1toV2(v1Source));
		expect(model.merges).toEqual([]);
	});
});

describe('v2 migration round-trip', () => {
	it('v1 source migrates to stable v2 YAML', async () => {
		const { migrateSource } = await import('../src/tableVersion');

		const v1Source = `---
columns:
  - { name: 任务, width: 200 }
  - { name: 状态, type: task-status }
styles:
  - { target: "1:1", bold: true, bg: "#e8f0fe" }
  - { target: "A2", bold: true }
---
| 任务   | 状态    |
| ------ | ------- |
| 设计   | done    |`;

		const v2Source = migrateSource(v1Source, 1);
		const model1   = parseTable(v2Source);
		const serial1  = serializeTable(model1);
		const model2   = parseTable(serial1);
		const serial2  = serializeTable(model2);

		expect(serial1).toBe(serial2);
		// 1:1 must migrate to "header", not be dropped
		expect(v2Source).toContain('target: header');
	});

	it('template styles migrate correctly: D3:D4 is rect not row-range', async () => {
		const { migrateSource } = await import('../src/tableVersion');
		const v2 = migrateSource(`---
columns:
  - { name: 功能 }
  - { name: 使用方式 }
  - { name: 状态, type: task-status }
  - { name: 备注 }
styles:
  - { target: "1:1", bold: true, bg: "#e8f0fe" }
  - { target: "A2:A4", bold: true }
  - { target: "D3:D4", bg: "#fef9c3", italic: true }
---
| 功能 | 使用方式 | 状态 | 备注 |
| ---- | -------- | ---- | ---- |
| r1   | r1       |      |      |
| r2   | r2       |      |      |
| r3   | r3       |      |      |`, 1);
		// D3:D4 must become a rect, not a row range
		expect(v2).not.toMatch(/target: r_\d+:r_\d+\n.*bg/s);
		expect(v2).toContain('target: header');
	});
});
