import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	loader: { '.yaml': 'text' },
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

/** Append all src/themes/*.css into styles.css after each build. */
function appendThemeCSS() {
	const themeDir = 'src/themes';
	const files = fs.readdirSync(themeDir).filter(f => f.endsWith('.css')).sort();
	if (files.length === 0) return;
	const separator = '\n\n/* ── Built-in themes (auto-generated — do not edit below) ──── */\n';
	const css = separator + files.map(f => fs.readFileSync(path.join(themeDir, f), 'utf8')).join('\n');
	fs.appendFileSync('styles.css', css);
}

if (prod) {
	await context.rebuild();
	appendThemeCSS();
	process.exit(0);
} else {
	appendThemeCSS();
	await context.watch();
}
