import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const gen  = process.argv[2] === 'generate';

/** Parse @theme-label-en / @theme-label-zh comment headers from CSS files and
 *  write src/themes/generated.ts so the renderer discovers themes automatically. */
function generateThemeMeta() {
	const themeDir = 'src/themes';
	if (!fs.existsSync(themeDir)) return;
	const files = fs.readdirSync(themeDir)
		.filter(f => f.endsWith('.css'))
		.sort();

	const themes = [];
	for (const file of files) {
		const css = fs.readFileSync(path.join(themeDir, file), 'utf8');
		const get = key => {
			const m = css.match(new RegExp(`\\/\\*\\s*@${key}:\\s*(.+?)\\s*\\*\\/`));
			return m ? m[1].trim() : null;
		};
		const labelEn = get('theme-label-en');
		const labelZh = get('theme-label-zh');
		if (!labelEn || !labelZh) continue;
		themes.push({ id: file.replace('.css', ''), labelEn, labelZh });
	}

	const rows = themes
		.map(t => `\t{ id: '${t.id}', labelEn: '${t.labelEn}', labelZh: '${t.labelZh}' },`)
		.join('\n');

	const out = `// Auto-generated by esbuild.config.mjs — do not edit directly.
// To add a theme: create src/themes/<id>.css with @theme-label-en and @theme-label-zh comments.

export interface ThemeMeta {
\tid: string;
\tlabelEn: string;
\tlabelZh: string;
}

export const BUILTIN_THEMES: readonly ThemeMeta[] = [
${rows}
] as const;

export const BUILTIN_THEME_IDS = BUILTIN_THEMES.map(t => t.id);
`;
	fs.writeFileSync(path.join(themeDir, 'generated.ts'), out);
	console.log(`[themes] generated.ts updated (${themes.length} themes: ${themes.map(t => t.id).join(', ')})`);
}

/** Extract the `title:` field from a template YAML file's front matter
 *  (between the first two `---` lines) — used as that template's button
 *  label, so authoring a template's own (already-localized) title is the
 *  only metadata a new template needs, no separate label convention. */
function extractTemplateTitle(content, fallback) {
	const fm = content.match(/^---\n([\s\S]*?)\n---/);
	const body = fm ? fm[1] : content;
	const m = body.match(/^title:\s*(.+)$/m);
	if (!m) return fallback;
	return m[1].trim().replace(/^["']|["']$/g, '');
}

/** Scan src/templates/<id>-en.yaml / <id>-zh.yaml pairs and write
 *  src/templates/generated.ts — same auto-discovery shape as generateThemeMeta,
 *  plus the actual YAML content (templates are consumed as parsed data, not
 *  linked as a stylesheet, so generated.ts embeds them as string imports).
 *  To add a template: drop in a new <id>-en.yaml/<id>-zh.yaml pair, each with
 *  its own `title:` field — no other code changes needed. */
function generateTemplateMeta() {
	const dir = 'src/templates';
	if (!fs.existsSync(dir)) return;
	const files = fs.readdirSync(dir).filter(f => f.endsWith('.yaml'));

	const ids = new Set();
	for (const file of files) {
		const m = file.match(/^(.+)-(en|zh)\.yaml$/);
		if (m) ids.add(m[1]);
	}

	const templates = [];
	for (const id of ids) {
		const enPath = path.join(dir, `${id}-en.yaml`);
		const zhPath = path.join(dir, `${id}-zh.yaml`);
		if (!fs.existsSync(enPath) || !fs.existsSync(zhPath)) {
			console.warn(`[templates] skipping "${id}" — needs both -en.yaml and -zh.yaml`);
			continue;
		}
		const enContent = fs.readFileSync(enPath, 'utf8');
		const zhContent = fs.readFileSync(zhPath, 'utf8');
		templates.push({
			id,
			labelEn: extractTemplateTitle(enContent, id),
			labelZh: extractTemplateTitle(zhContent, id),
		});
	}

	// "demo" always sorts first (the default preview/first choice); everything
	// else alphabetical — keeps a stable, deliberate default without requiring
	// every future template to carry an explicit ordering field.
	templates.sort((a, b) => {
		if (a.id === 'demo') return -1;
		if (b.id === 'demo') return 1;
		return a.id.localeCompare(b.id);
	});

	const imports = templates
		.map(t => `import ${t.id.replace(/-/g, '_')}_en from './${t.id}-en.yaml';\nimport ${t.id.replace(/-/g, '_')}_zh from './${t.id}-zh.yaml';`)
		.join('\n');
	const rows = templates
		.map(t => `\t{ id: '${t.id}', labelEn: ${JSON.stringify(t.labelEn)}, labelZh: ${JSON.stringify(t.labelZh)}, en: ${t.id.replace(/-/g, '_')}_en, zh: ${t.id.replace(/-/g, '_')}_zh },`)
		.join('\n');

	const out = `// Auto-generated by esbuild.config.mjs — do not edit directly.
// To add a template: create src/templates/<id>-en.yaml and <id>-zh.yaml, each
// with a \`title:\` field in its YAML front matter (used as the button label).
${imports}

export interface TemplateMeta {
\tid: string;
\tlabelEn: string;
\tlabelZh: string;
\ten: string;
\tzh: string;
}

export const BUILTIN_TEMPLATES: readonly TemplateMeta[] = [
${rows}
] as const;
`;
	fs.writeFileSync(path.join(dir, 'generated.ts'), out);
	console.log(`[templates] generated.ts updated (${templates.length} templates: ${templates.map(t => t.id).join(', ')})`);
}

/** Runs a git subcommand and returns trimmed stdout, throwing on any failure
 *  (missing git, not a repo, etc.) — the caller decides what "can't generate
 *  a changelog right now" means, this just refuses to silently return ''. */
function git(args) {
	return execFileSync('git', args, { encoding: 'utf8' }).trim();
}

// This repo started life as a `git clone` of the community
// obsidian-sample-plugin template, carrying that template's own ~100 commits
// of history (upstream maintainers' scaffolding, README/build-tooling
// churn — "Initial commit!", "Use rollup for bundling.", etc., none of it
// Rich Table's own work). This is the first commit actually authored as
// this plugin; the very first tag has no previous tag to bound its range
// (see buildChangelogEntries below) and would otherwise list every one of
// those template commits back to the beginning of time.
const FORK_COMMIT = 'ea0c440';

/** Builds one changelog entry per real (non-nightly) version tag: its date and
 *  the commit-message titles added since the previous version tag. Throws if
 *  git history isn't available (e.g. lint.yml's shallow `actions/checkout`,
 *  which has no tags at all) — generateChangelogMeta below catches that and
 *  leaves the last COMMITTED generated.ts alone rather than blanking it, so a
 *  shallow-clone CI build still type-checks against real (if stale) data. */
function buildChangelogEntries() {
	const tags = git(['tag', '--list', '--sort=version:refname'])
		.split('\n').map(s => s.trim()).filter(Boolean)
		.filter(tag => /^\d+\.\d+\.\d+$/.test(tag)); // excludes nightly-YYYY-MM-DD tags
	if (tags.length === 0) throw new Error('no version tags found');

	// The oldest tag's range starts at FORK_COMMIT rather than the dawn of
	// history — but only if that commit is actually reachable (a shallow or
	// otherwise truncated clone might not have it); falls back to the
	// unbounded range rather than failing the whole build over one tag's
	// worth of extra noise.
	let firstTagRange = tags[0];
	try {
		git(['rev-parse', '--verify', `${FORK_COMMIT}^{commit}`]);
		firstTagRange = `${FORK_COMMIT}^..${tags[0]}`;
	} catch {
		console.warn(`[changelog] fork commit ${FORK_COMMIT} not reachable — the oldest tag's entry will include pre-fork template history`);
	}

	const entries = tags.map((tag, i) => {
		const prevTag = tags[i - 1];
		const range = prevTag ? `${prevTag}..${tag}` : firstTagRange;
		const date = git(['log', '-1', '--format=%ad', '--date=short', tag]);
		const changes = git(['log', '--format=%s', range])
			.split('\n').map(s => s.trim())
			.filter(s => s && s !== `chore: release ${tag}`); // the tag's own release commit is noise here
		return { version: tag, date, changes };
	});
	entries.reverse(); // newest first
	return entries;
}

/** Regenerates src/changelog/generated.ts from git tags — see buildChangelogEntries.
 *  Skips (keeping whatever's already committed) when git history isn't usable,
 *  same shallow-clone reasoning as that function's own doc comment. */
function generateChangelogMeta() {
	const outPath = 'src/changelog/generated.ts';
	let entries;
	try {
		entries = buildChangelogEntries();
	} catch (err) {
		console.warn(`[changelog] skipping regeneration (${err.message}) — keeping existing generated.ts`);
		return;
	}

	const esc = s => JSON.stringify(s);
	const rows = entries.map(e => {
		const changeLines = e.changes.map(c => `\t\t${esc(c)},`).join('\n');
		return `\t{ version: ${esc(e.version)}, date: ${esc(e.date)}, changes: [\n${changeLines}\n\t] },`;
	}).join('\n');

	const out = `// Auto-generated by esbuild.config.mjs — do not edit directly.
// Rebuilt from git tags/commit history on every build (skipped, keeping this
// file as-is, when git history isn't available — e.g. a shallow CI checkout).

export interface ChangelogEntry {
\tversion: string;
\tdate: string;
\tchanges: string[];
}

export const CHANGELOG: readonly ChangelogEntry[] = [
${rows}
];
`;
	fs.writeFileSync(outPath, out);
	console.log(`[changelog] generated.ts updated (${entries.length} versions, latest ${entries[0]?.version ?? 'n/a'})`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	loader: { '.yaml': 'text' },
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

/** Append all src/themes/*.css into styles.css after each build.
 *  Truncates any previously appended themes section first so repeated builds
 *  don't accumulate stale CSS rules that can't be overridden. */
function appendThemeCSS() {
	const themeDir = 'src/themes';
	if (!fs.existsSync(themeDir)) return;
	const files = fs.readdirSync(themeDir).filter(f => f.endsWith('.css')).sort();
	if (files.length === 0) return;
	const separator = '\n\n/* ── Built-in themes (auto-generated — do not edit below) ──── */\n';
	// Strip any previously appended themes block before re-appending.
	let base = fs.readFileSync('styles.css', 'utf8');
	const cutIdx = base.indexOf(separator);
	if (cutIdx !== -1) base = base.slice(0, cutIdx);
	const css = base + separator + files.map(f => fs.readFileSync(path.join(themeDir, f), 'utf8')).join('\n');
	fs.writeFileSync('styles.css', css);
}

if (gen) {
	generateThemeMeta();
	generateTemplateMeta();
	generateChangelogMeta();
	process.exit(0);
} else if (prod) {
	generateThemeMeta();
	generateTemplateMeta();
	generateChangelogMeta();
	await context.rebuild();
	appendThemeCSS();
	process.exit(0);
} else {
	generateThemeMeta();
	generateTemplateMeta();
	generateChangelogMeta();
	appendThemeCSS();
	await context.watch();
}
