// Auto-generated by esbuild.config.mjs — do not edit directly.
// To add a template: create src/templates/<id>-en.yaml and <id>-zh.yaml, each
// with a `title:` field in its YAML front matter (used as the button label).
import demo_en from './demo-en.yaml';
import demo_zh from './demo-zh.yaml';
import cornell_en from './cornell-en.yaml';
import cornell_zh from './cornell-zh.yaml';

export interface TemplateMeta {
	id: string;
	labelEn: string;
	labelZh: string;
	en: string;
	zh: string;
}

export const BUILTIN_TEMPLATES: readonly TemplateMeta[] = [
	{ id: 'demo', labelEn: "Rich Table Demo", labelZh: "Rich Table 示例", en: demo_en, zh: demo_zh },
	{ id: 'cornell', labelEn: "Cornell Notes", labelZh: "康奈尔笔记", en: cornell_en, zh: cornell_zh },
] as const;
