// Auto-generated by esbuild.config.mjs — do not edit directly.
// To add a theme: create src/themes/<id>.css with @theme-label-en and @theme-label-zh comments.

export interface ThemeMeta {
	id: string;
	labelEn: string;
	labelZh: string;
}

export const BUILTIN_THEMES: readonly ThemeMeta[] = [
	{ id: 'academic', labelEn: 'Academic 📐', labelZh: '学术 📐' },
	{ id: 'grid', labelEn: 'Grid 🔲', labelZh: '网格 🔲' },
	{ id: 'plain', labelEn: 'Plain 🙂', labelZh: '朴素 🙂' },
] as const;

export const BUILTIN_THEME_IDS = BUILTIN_THEMES.map(t => t.id);
