/**
 * v2 serializer.
 *
 * Outputs:
 *   1. YAML front-matter (deterministic — fixed field order, stringifyYaml)
 *   2. An HTML comment warning users not to edit the pipe table manually
 *   3. A generated pipe table mirror (read-only, for human readability)
 *
 * The pipe table is derived from the model; it is NOT a data source.
 * On the next write-back the table is fully regenerated from the YAML.
 *
 * MIRROR_LIMIT: tables with more than this many data rows only mirror the
 * first MIRROR_LIMIT rows to avoid bloating the file.
 */

import { stringifyYaml } from 'obsidian';
import type { SheetDefV2, TableModelV2, WorkbookV3 } from './model';

const MIRROR_LIMIT = 200;
const MIRROR_COMMENT =
	'<!-- Generated by Rich Table. Do not edit below — ' +
	'data source is the YAML front-matter above. -->';

export function serializeTable(model: TableModelV2): string {
	const obj: Record<string, unknown> = { version: 2, ...serializeModelFields(model) };
	const parts: string[] = ['---', stringifyYaml(obj).trimEnd(), '---', ''];
	parts.push(MIRROR_COMMENT);
	parts.push(buildPipeTable(model));
	return parts.join('\n');
}

/**
 * Serializes a multi-sheet workbook. Deliberately has NO pipe-table mirror
 * (unlike `serializeTable`) — a per-sheet mirror would need the block to
 * alternate YAML/markdown chunks with no reliable way to tell them apart on
 * the next parse, and a single combined mirror for just the active sheet
 * would be a confusing half-measure, so v3 tables simply aren't readable in
 * raw markdown without the plugin (a deliberate, accepted tradeoff — see the
 * multi-sheet design discussion). Determinism (parse→serialize→parse→
 * serialize byte-stable, same Principle-3 guarantee `test/v2.roundtrip.test.ts`
 * already checks for single-sheet tables) is what keeps re-serializing every
 * sheet on every write-back safe — editing one sheet never perturbs another
 * sheet's YAML text, because `serializeModelFields`/`stringifyYaml` produce
 * the same output for the same data regardless of what else is in the array.
 */
export function serializeWorkbook(workbook: WorkbookV3): string {
	const obj: Record<string, unknown> = { version: 3 };
	if (workbook.title) obj.title = workbook.title;
	obj.active_sheet = workbook.activeSheetId;
	obj.sheets = workbook.sheets.map(serializeSheet);
	return ['---', stringifyYaml(obj).trimEnd(), '---', ''].join('\n');
}

function serializeSheet(sheet: SheetDefV2): Record<string, unknown> {
	const entry: Record<string, unknown> = { id: sheet.id };
	if (sheet.name) entry.name = sheet.name;
	if (sheet.tabColor) entry.tabColor = sheet.tabColor;
	if (sheet.tabTextColor) entry.tabTextColor = sheet.tabTextColor;
	Object.assign(entry, serializeModelFields(sheet));
	return entry;
}

// ── YAML block ────────────────────────────────────────────────────────────────

/** Builds every field of a single sheet's model EXCEPT `version` — shared by
 *  `serializeTable` (top-level object) and `serializeSheet` (one `sheets[]`
 *  entry) since a sheet's own data is exactly a single-sheet v2 table's data. */
function serializeModelFields(m: TableModelV2): Record<string, unknown> {
	const obj: Record<string, unknown> = {};

	if (m.title)   obj.title   = m.title;

	obj.columns = m.columns.map(c => {
		const entry: Record<string, unknown> = { id: c.id, name: c.name };
		if (c.hidden)  entry.hidden = true;
		if (c.type)    entry.type   = c.type;
		if (c.width)   entry.width  = c.width;
		if (c.align)   entry.align  = c.align;
		if (c.filter && c.filter.length > 0) entry.filter = c.filter;
		return entry;
	});

	obj.rows = m.rows.map(r => {
		const entry: Record<string, unknown> = { id: r.id };
		if (r.hidden)           entry.hidden = true;
		if (r.height && r.height > 0) entry.height = r.height;
		// Cells: only store non-empty values (sparse)
		const cells: Record<string, string> = {};
		for (const col of m.columns) {
			const v = r.cells[col.id] ?? '';
			if (v !== '') cells[col.id] = v;
		}
		entry.cells = cells;
		if (r.formulas && Object.keys(r.formulas).length > 0) entry.formulas = r.formulas;
		return entry;
	});

	if (m.merges.length > 0) {
		obj.merges = m.merges.map(mg => ({ anchor: mg.anchor, end: mg.end }));
	}

	if (m.styles.length > 0) {
		obj.styles = m.styles.map(s => {
			const e: Record<string, unknown> = { target: s.target };
			if (s.bg)     e.bg     = s.bg;
			if (s.color)  e.color  = s.color;
			if (s.bold)   e.bold   = true;
			if (s.italic) e.italic = true;
			if (s.size)   e.size   = s.size;
			return e;
		});
	}

	if (m.footer) obj.footer = m.footer;
	if (m.theme)  obj.theme  = m.theme;
	if (m.locked) obj.locked = true;
	if (m.collapsed) obj.collapsed = true;
	if (m.sort) obj.sort = { colId: m.sort.colId, dir: m.sort.dir };
	if (m.aggregate && m.aggregate.length > 0) obj.aggregate = m.aggregate;
	if (typeof m.freezeRows === 'number') obj.freezeRows = m.freezeRows;
	if (typeof m.freezeCols === 'number') obj.freezeCols = m.freezeCols;
	if (typeof m.viewWidth === 'number') obj.viewWidth = m.viewWidth;
	if (typeof m.viewHeight === 'number') obj.viewHeight = m.viewHeight;
	if (m.statusBarMode) obj.statusBarMode = m.statusBarMode;
	if (typeof m.statusBarScrollWidth === 'number') obj.statusBarScrollWidth = m.statusBarScrollWidth;
	if (m.views && m.views.length > 0) {
		obj.views = m.views.map(v => {
			const e: Record<string, unknown> = { id: v.id, type: v.type };
			// Absent = derive the display name from the column header at render
			// time — only written once the user explicitly renames the view.
			if (v.name) e.name = v.name;
			if (v.kanban) e.kanban = { groupByColId: v.kanban.groupByColId };
			if (v.calendar) e.calendar = { dateColId: v.calendar.dateColId };
			return e;
		});
		// Only meaningful alongside the views[] entries above.
		if (m.activeViewId) obj.activeViewId = m.activeViewId;
	}

	return obj;
}

// ── Pipe table mirror ─────────────────────────────────────────────────────────

function buildPipeTable(m: TableModelV2): string {
	const cols = m.columns.filter(c => !c.hidden);
	if (cols.length === 0) return '';

	// Collect the occupied set for merged cells
	const occupied = buildOccupiedV2(m);

	// Header row
	const headerCells = cols.map(c => c.name);
	const rows: string[][] = [headerCells];

	const dataRows = m.rows.slice(0, MIRROR_LIMIT);
	const truncated = m.rows.length > MIRROR_LIMIT;

	for (const row of dataRows) {
		if (row.hidden) continue;
		const cells = cols.map(col => {
			const key = `${row.id}.${col.id}`;
			if (occupied.has(key)) return ''; // covered by a merge
			// Mirror multiline content: use <br> so the pipe table stays valid (single row)
			return (row.cells[col.id] ?? '').replace(/\n/g, '<br>');
		});
		rows.push(cells);
	}

	// Compute column widths for alignment
	const widths = cols.map((_, ci) =>
		Math.max(3, ...rows.map(r => displayLen(r[ci] ?? ''))),
	);

	const lines: string[] = [];
	// Header
	lines.push(formatRow(rows[0]!, widths));
	// Separator
	lines.push('| ' + widths.map(w => '-'.repeat(w)).join(' | ') + ' |');
	// Data rows
	for (let i = 1; i < rows.length; i++) {
		lines.push(formatRow(rows[i]!, widths));
	}

	if (truncated) {
		lines.push(`<!-- ${m.rows.length - MIRROR_LIMIT} more rows not shown in mirror -->`);
	}

	return lines.join('\n');
}

/** Exported for reuse by the "copy as Markdown" clipboard action in renderer.ts. */
export function formatRow(cells: string[], widths: number[]): string {
	return '| ' + cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(' | ') + ' |';
}

export function displayLen(s: string): number {
	// Rough CJK width estimate (each CJK char ≈ 2 monospace units)
	let len = 0;
	for (const ch of s) {
		len += ch.charCodeAt(0) > 0x2e7f ? 2 : 1;
	}
	return len;
}

/** Build the set of "rowId.colId" keys that are COVERED (not anchor) by a merge. */
function buildOccupiedV2(m: TableModelV2): Set<string> {
	const occupied = new Set<string>();
	for (const mg of m.merges) {
		const [anchorRowId, anchorColId] = mg.anchor.split('.');
		const [endRowId,    endColId]    = mg.end.split('.');
		if (!anchorRowId || !anchorColId || !endRowId || !endColId) continue;
		const ri1 = m.rows.findIndex(r => r.id === anchorRowId);
		const ri2 = m.rows.findIndex(r => r.id === endRowId);
		const ci1 = m.columns.findIndex(c => c.id === anchorColId);
		const ci2 = m.columns.findIndex(c => c.id === endColId);
		for (let ri = Math.min(ri1, ri2); ri <= Math.max(ri1, ri2); ri++) {
			for (let ci = Math.min(ci1, ci2); ci <= Math.max(ci1, ci2); ci++) {
				if (ri === ri1 && ci === ci1) continue; // anchor keeps content
				const rowId = m.rows[ri]?.id;
				const colId = m.columns[ci]?.id;
				if (rowId && colId) occupied.add(`${rowId}.${colId}`);
			}
		}
	}
	return occupied;
}
