/**
 * v2 serializer.
 *
 * Outputs:
 *   1. YAML front-matter (deterministic — fixed field order, stringifyYaml)
 *   2. An HTML comment warning users not to edit the pipe table manually
 *   3. A generated pipe table mirror (read-only, for human readability)
 *
 * The pipe table is derived from the model; it is NOT a data source.
 * On the next write-back the table is fully regenerated from the YAML.
 *
 * MIRROR_LIMIT: tables with more than this many data rows only mirror the
 * first MIRROR_LIMIT rows to avoid bloating the file.
 */

import { stringifyYaml } from 'obsidian';
import type { TableModelV2 } from './model';

const MIRROR_LIMIT = 200;
const MIRROR_COMMENT =
	'<!-- Generated by Rich Table. Do not edit below — ' +
	'data source is the YAML front-matter above. -->';

export function serializeTable(model: TableModelV2): string {
	const parts: string[] = ['---', buildYaml(model).trimEnd(), '---', ''];
	parts.push(MIRROR_COMMENT);
	parts.push(buildPipeTable(model));
	return parts.join('\n');
}

// ── YAML block ────────────────────────────────────────────────────────────────

function buildYaml(m: TableModelV2): string {
	// Fixed field order for deterministic output.
	const obj: Record<string, unknown> = { version: 2 };

	if (m.title)   obj.title   = m.title;

	obj.columns = m.columns.map(c => {
		const entry: Record<string, unknown> = { id: c.id, name: c.name };
		if (c.hidden)  entry.hidden = true;
		if (c.type)    entry.type   = c.type;
		if (c.width)   entry.width  = c.width;
		if (c.align)   entry.align  = c.align;
		if (c.filter && c.filter.length > 0) entry.filter = c.filter;
		return entry;
	});

	obj.rows = m.rows.map(r => {
		const entry: Record<string, unknown> = { id: r.id };
		if (r.hidden)           entry.hidden = true;
		if (r.height && r.height > 0) entry.height = r.height;
		// Cells: only store non-empty values (sparse)
		const cells: Record<string, string> = {};
		for (const col of m.columns) {
			const v = r.cells[col.id] ?? '';
			if (v !== '') cells[col.id] = v;
		}
		entry.cells = cells;
		return entry;
	});

	if (m.merges.length > 0) {
		obj.merges = m.merges.map(mg => ({ anchor: mg.anchor, end: mg.end }));
	}

	if (m.styles.length > 0) {
		obj.styles = m.styles.map(s => {
			const e: Record<string, unknown> = { target: s.target };
			if (s.bg)     e.bg     = s.bg;
			if (s.color)  e.color  = s.color;
			if (s.bold)   e.bold   = true;
			if (s.italic) e.italic = true;
			if (s.size)   e.size   = s.size;
			return e;
		});
	}

	if (m.footer) obj.footer = m.footer;
	if (m.theme)  obj.theme  = m.theme;
	if (m.locked) obj.locked = true;
	if (m.collapsed) obj.collapsed = true;
	if (m.sort) obj.sort = { colId: m.sort.colId, dir: m.sort.dir };

	return stringifyYaml(obj);
}

// ── Pipe table mirror ─────────────────────────────────────────────────────────

function buildPipeTable(m: TableModelV2): string {
	const cols = m.columns.filter(c => !c.hidden);
	if (cols.length === 0) return '';

	// Collect the occupied set for merged cells
	const occupied = buildOccupiedV2(m);

	// Header row
	const headerCells = cols.map(c => c.name);
	const rows: string[][] = [headerCells];

	const dataRows = m.rows.slice(0, MIRROR_LIMIT);
	const truncated = m.rows.length > MIRROR_LIMIT;

	for (const row of dataRows) {
		if (row.hidden) continue;
		const cells = cols.map(col => {
			const key = `${row.id}.${col.id}`;
			if (occupied.has(key)) return ''; // covered by a merge
			// Mirror multiline content: use <br> so the pipe table stays valid (single row)
			return (row.cells[col.id] ?? '').replace(/\n/g, '<br>');
		});
		rows.push(cells);
	}

	// Compute column widths for alignment
	const widths = cols.map((_, ci) =>
		Math.max(3, ...rows.map(r => displayLen(r[ci] ?? ''))),
	);

	const lines: string[] = [];
	// Header
	lines.push(formatRow(rows[0]!, widths));
	// Separator
	lines.push('| ' + widths.map(w => '-'.repeat(w)).join(' | ') + ' |');
	// Data rows
	for (let i = 1; i < rows.length; i++) {
		lines.push(formatRow(rows[i]!, widths));
	}

	if (truncated) {
		lines.push(`<!-- ${m.rows.length - MIRROR_LIMIT} more rows not shown in mirror -->`);
	}

	return lines.join('\n');
}

/** Exported for reuse by the "copy as Markdown" clipboard action in renderer.ts. */
export function formatRow(cells: string[], widths: number[]): string {
	return '| ' + cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(' | ') + ' |';
}

export function displayLen(s: string): number {
	// Rough CJK width estimate (each CJK char ≈ 2 monospace units)
	let len = 0;
	for (const ch of s) {
		len += ch.charCodeAt(0) > 0x2e7f ? 2 : 1;
	}
	return len;
}

/** Build the set of "rowId.colId" keys that are COVERED (not anchor) by a merge. */
function buildOccupiedV2(m: TableModelV2): Set<string> {
	const occupied = new Set<string>();
	for (const mg of m.merges) {
		const [anchorRowId, anchorColId] = mg.anchor.split('.');
		const [endRowId,    endColId]    = mg.end.split('.');
		if (!anchorRowId || !anchorColId || !endRowId || !endColId) continue;
		const ri1 = m.rows.findIndex(r => r.id === anchorRowId);
		const ri2 = m.rows.findIndex(r => r.id === endRowId);
		const ci1 = m.columns.findIndex(c => c.id === anchorColId);
		const ci2 = m.columns.findIndex(c => c.id === endColId);
		for (let ri = Math.min(ri1, ri2); ri <= Math.max(ri1, ri2); ri++) {
			for (let ci = Math.min(ci1, ci2); ci <= Math.max(ci1, ci2); ci++) {
				if (ri === ri1 && ci === ci1) continue; // anchor keeps content
				const rowId = m.rows[ri]?.id;
				const colId = m.columns[ci]?.id;
				if (rowId && colId) occupied.add(`${rowId}.${colId}`);
			}
		}
	}
	return occupied;
}
